# Generated by Django 2.1.2 on 2018-10-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181003_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='med_cardio_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='med_cardio_refresher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='obgyn_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='obgyn_refresher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='pediatrics_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='pediatrics_refresher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='trauma_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gvk_emri_demographics',
            name='trauma_refresher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='years_of_experience',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
