# Generated by Django 2.1.3 on 2018-12-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181221_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuserdata',
            name='feedback',
        ),
    ]
