# Generated by Django 2.1.2 on 2018-11-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181004_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='questions/')),
                ('media_type', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='quiz.QuestionMedia'),
        ),
    ]
