# Generated by Django 2.1.3 on 2018-12-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_questionuserdata_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='questionuserdata',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Feedback'),
        ),
    ]
