# Generated by Django 2.1.2 on 2018-11-03 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20181103_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_time',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
