# Generated by Django 2.1.3 on 2018-12-31 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181227_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='quiz.Tag'),
        ),
        migrations.AlterField(
            model_name='categoryuserdata',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='quiz.QuestionMedia'),
        ),
        migrations.AlterField(
            model_name='questionuserdata',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='quiz.Answer'),
        ),
        migrations.AlterField(
            model_name='questionuserdata',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Feedback'),
        ),
        migrations.AlterField(
            model_name='questionuserdata',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
