# Generated by Django 2.1.3 on 2019-02-06 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190206_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='practice_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(9999, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
