# Generated by Django 2.1.3 on 2019-02-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20190207_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuserdata',
            name='quiz_userdata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='quiz.QuizUserData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='can_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='questionuserdata',
            unique_together={('question', 'student', 'quiz_userdata')},
        ),
        migrations.AlterUniqueTogether(
            name='quizuserdata',
            unique_together=set(),
        ),
    ]
