# Generated by Django 2.1.3 on 2019-02-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20190211_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuserdata',
            name='quiz',
        ),
    ]
