# Generated by Django 2.1.3 on 2019-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_questionuserdata_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionuserdata',
            options={'get_latest_by': 'time_started'},
        ),
        migrations.AlterModelOptions(
            name='quizuserdata',
            options={'get_latest_by': 'time_started'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.IntegerField(default=-1),
        ),
    ]
