# Generated by Django 2.1.3 on 2019-02-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quiz_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='completed_survey',
            new_name='completed_demographic_survey',
        ),
        migrations.AddField(
            model_name='student',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_prompt_required',
            field=models.BooleanField(default=True),
        ),
    ]
