# Generated by Django 2.1.5 on 2019-04-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='badges'),
        ),
    ]
