# Generated by Django 2.1.5 on 2019-04-25 01:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20190404_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/static/'), upload_to='badges'),
        ),
    ]
