# Generated by Django 2.1.5 on 2019-04-25 03:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20190425_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/badges', location='/static/'), upload_to='badges'),
        ),
    ]
