# Generated by Django 2.2.1 on 2019-05-27 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20190426_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('QuizStart', 'QuizStart'), ('QuizEnd', 'QuizEnd'), ('QuestionStart', 'QuestionStart'), ('QuestionEnd', 'QuestionEnd'), ('BadgeEarn', 'BadgeEarn'), ('ProfileUpdate', 'ProfileUpdate'), ('Login', 'Login')], max_length=32)),
                ('device_family', models.CharField(max_length=256)),
                ('browser_family', models.CharField(max_length=256)),
                ('browser_version', models.CharField(max_length=256)),
                ('os_family', models.CharField(max_length=256)),
                ('os_version', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='education_level',
            field=models.CharField(default='LPS', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='job',
            field=models.CharField(default='OTH', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.CharField(default='OTH', max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('QuizStart', 'QuizStart'), ('QuizEnd', 'QuizEnd'), ('QuestionStart', 'QuestionStart'), ('QuestionEnd', 'QuestionEnd'), ('BadgeEarn', 'BadgeEarn'), ('ProfileUpdate', 'ProfileUpdate'), ('Login', 'Login')], max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Badge')),
                ('device_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.DeviceData')),
                ('question_ud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.QuestionUserData')),
                ('quiz_ud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.QuizUserData')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.Student')),
            ],
        ),
    ]
