# Generated by Django 2.2.1 on 2019-05-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20190527_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Badge'),
        ),
        migrations.AlterField(
            model_name='event',
            name='device_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.DeviceData'),
        ),
        migrations.AlterField(
            model_name='event',
            name='question_ud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.QuestionUserData'),
        ),
        migrations.AlterField(
            model_name='event',
            name='quiz_ud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.QuizUserData'),
        ),
    ]
