# Generated by Django 2.2.3 on 2020-04-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20200402_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_covid19_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='COVID19_Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_related_work', models.BooleanField()),
                ('register_reason', models.CharField(choices=[('SBS', 'Suggested by supervisor'), ('DWF', 'Discussion with friends'), ('SMP', 'Social media post')], max_length=3)),
                ('cared_for_covid', models.BooleanField()),
                ('cared_for_covid_possible', models.BooleanField()),
                ('confident_covid_care', models.CharField(choices=[('SA', 'Strongly Agree'), ('A', 'Agree'), ('N', 'Neither Agree nor Disagree'), ('D', 'Disagree'), ('SD', 'Strongly Disagree')], max_length=3)),
                ('ppe_access', models.CharField(choices=[('SA', 'Strongly Agree'), ('A', 'Agree'), ('N', 'Neither Agree nor Disagree'), ('D', 'Disagree'), ('SD', 'Strongly Disagree')], max_length=3)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Student')),
            ],
        ),
    ]
