# Generated by Django 2.2.3 on 2020-04-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20200404_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
