# Generated by Django 3.0.5 on 2020-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20200406_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscribed_to_emails',
            field=models.BooleanField(default=True),
        ),
    ]
