# Generated by Django 3.0.5 on 2021-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20210330_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='whatsapp_notifs',
            field=models.BooleanField(default=False),
        ),
    ]
