# Generated by Django 3.0.5 on 2021-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_student_whatsapp_notifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='quiz.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_of',
            field=models.ManyToManyField(related_name='instructors', to='quiz.Course'),
        ),
    ]
