# Generated by Django 3.0.5 on 2021-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20210422_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
